### ISSUE TITLE
[Bug]: 无法正常运行

### ISSUE THREAD

**Issue by htxzdfunny** [quizhizhe/LLCheckBag#7]
### Describe the bug

加载插件时出错:  
```powershell
21:35:27.609 ERROR [LeviLamina] player-bag-manager 加载失败
21:35:27.610 ERROR [LeviLamina] C++ Exception: std::system_error, from <LeviLamina>:
21:35:27.613 ERROR [LeviLamina] [0x0000007F:system] 找不到指定的程序。
21:35:27.614 ERROR [LeviLamina] 依赖诊断：
21:35:27.614 ERROR [LeviLamina]    模块： D:\MCServers\j8qworld\plugins\player-bag-manager\player-bag-manager.dll
21:35:27.614 ERROR [LeviLamina]    缺少符号：
21:35:27.614 ERROR [LeviLamina]    |- LeviLamina.dll
21:35:27.615 ERROR [LeviLamina]    |---- ?print@OutputStream@Logger@ll@@AEBAXV?$basic_string_view@DU?$char_traits@D@std@@@std@@@Z
21:35:27.615 ERROR [LeviLamina]    |     private: void __cdecl ll::Logger::OutputStream::print(class std::basic_string_view<char, struct std::char_traits<char>>) co
nst
```

### To Reproduce

1. 从 action 下载最新构建 ( https://github.com/quizhizhe/PlayerBagManager/actions/runs/8594000168 )
2. 解压后将文件放入 plugins 文件夹中
3. 重启服务器加载

### Expected behavior

正常加载并打印log

### Screenshots

![控制台截图](https://github.com/quizhizhe/PlayerBagManager/assets/54425771/dae151ef-be28-47ab-b1ec-2dd351465ac4)
![目录](https://github.com/quizhizhe/PlayerBagManager/assets/54425771/8f9af004-9930-4b51-9264-97e418c1176a)

### Platform

Windows Server 2019 Datacenter 10.0.17763

### BDS Version

1.20.81.01(ProtocolVersion 671)

### LeviLamina Version

LeviLamina-0.12.4+935b0d8ee

### Version

d937cb8

### Additional context

我在想是不是我的安装方法有误（

**Comment by htxzdfunny** [comment]
补充一下 plugins 目录是这样的  
![image](https://github.com/quizhizhe/PlayerBagManager/assets/54425771/b3ce3f2b-227e-4c9f-bf3e-d676e493b553)

**Comment by quizhizhe** [comment]
目前没有适配ll3，也就是LeviLamina
